version: "3.4"

services:
  dashboard_dikda:
    image: node:alpine
    container_name: dashboard_dikda
    ports:
      - 3001:3001
    volumes:
      - type: bind
        source: ./
        target: /srv/app
