version: "3.3"
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - "/app/node_modules"
      - "./:/app"
    command: sh -c "chmod -R 755 /app/node_modules/.vite && npm start"
